/*!
 * Agency: manolab, LLC
 * Project: Gold Medal Wine / Craft Beer Club
 * Modified: 11/21/2018
 * Developer: Thomas Paine / Christian Fillies
 *
 */
var CartClass=function(){var s="fadeInDown",n="fadeOutUp",i;this.qCTimer=null;var o=this.startTimer=function(t,e){this.qCTimer=window.setTimeout(function(){$(t).removeClass(s).addClass(n)},e),i=this.qCTimer};this.debug=function(t,e){var a;if(-1<window.location.toString().toLowerCase().indexOf("debugcart"))return null!=t&&(null!=e?console.debug("cart: "+t,e):console.debug("cart: "+t)),!0},this.error=function(t,e){var a;if(-1<window.location.toString().toLowerCase().indexOf("debugcart"))return null!=t&&(null!=e?console.error("cart: "+t,e):console.error("cart: "+t)),!0},this.init=function(){this.debug("init",this)},this.refreshCart=function(t){null==t&&(t=!0)/*default to true because most of the time we want to show this except when we first load a page*/,this.debug("refreshCart",t),$("#cart_summary_container").load("/api/output/gm_cart_summary?_output=html&_template=kmYiDpAJxUadMzYGZS2Iyg",function(){document.cart.debug("refreshCart : finished loading summary",t),$("#cart_summary_widget")&&0<$("#cart_summary_widget").html().length&&(document.cart.debug("refreshCart : cart found, loading small cart",t),
/*if a cart exists, load the small cart*/
$("#cart_contents").load("/api/content/7GG5G44ssk62ySaoYqMPTQ",function(){document.cart.showSmallCart(".navbar-cart"),t&&document.cart.quickCart(".quick-cart",7e3,!0),$('[data-toggle~="showQuickCart"]').hover(function(){document.cart.quickCart(".quick-cart",0,!1)}),document.cart.smallCartSpinner("hide")})),$("#cart_summary_container").show()})},this.qCCounter=function(t){this.debug("qCCounter",t),$(t).hasClass("bounceIn")?$(t).removeClass("bounceIn").addClass("bounceIn"):$(t).addClass("bounceIn")},this.smallCartSpinner=function(t){this.debug("smallCartSpinner",t);var e="auto",a="._smallCartSpinner";"hide"===t&&(t=$(a),e=!0);var r="string"==typeof t?$(t):t;void 0===t&&(r=$(a)),r.hasClass("hidden")&&"auto"===e?r.removeClass("hidden"):r.addClass("hidden")},this.showSmallCart=function(t){this.debug("showSmallCart",t),$(t).is(":visible")&&($(".navbar-top").addClass("navbar-with-small-cart"),this.qCCounter("#cartCounter"))},this.quickCart=function(e,t,a){this.debug("quickCart",t);var r=$(e);!0===a&&clearTimeout(this.qCTimer),t&&0<t?r.hasClass(s)?this.startTimer(r,t):(r.hasClass(n)||r.hasClass("hidden"))&&(clearTimeout(this.qCTimer),r.removeClass(n).removeClass("hidden").addClass(s),!0===a&&clearTimeout(this.qCTimer),this.startTimer(r,t)):r.removeClass(n).removeClass("hidden").addClass(s),$("html, body div").one("click",function(t){$(e).is(t.target)||0!==$(e).has(t.target).length||(t.preventDefault(),o($(e),0))}),$(e).on("mouseenter mouseover",function(t){clearTimeout(i)})},this.addItemByForm=function(t){return this.debug("addItemByForm",t),0==$(t).length?(this.error("addItemByForm : unable to find formID",t),alert("Internal error, unable to add item to cart")):$.ajax({url:"/api/output/gm_cart_addItem",type:"post",data:$(t).serialize(),dataType:"json",beforeSend:function(t,e){document.cart.smallCartSpinner()}}).done(function(t){document.cart.debug("addItemByForm done",t);var e=!0,a;t&&Array.isArray(t)?t[0].Successful&&"true"==t[0].Successful.toLowerCase()?document.cart.refreshCart():t[0].Message&&(a=t[0].Message,e=!1):(this.error("addItemByForm invalid result",t),e=!1,t.Message?a=t.Message:t.Messages&&(a=t.Messages)),e||(a||(a="We were unable to add this item to you cart. Please try again"),document.cart.smallCartSpinner("hide"),alert(a))}),!1}};/*cartClass*/document.cart=new CartClass;
/* cart.js */